### PR TITLE
Casing issue fixed

### PR DESCRIPTION
**Pull request by petems**
Please check the following items before submitting a PR -- thank you!

Note that this project is released with a Contributor Code of Conduct.
By participating in this project you agree to abide by its terms.
[Contributor Code of Conduct](https://voxpupuli.org/coc/).
- [x] There is no existing PR that addresses this problem
- [x] Mentioned any existing issues in your commit so they get linked and
  closed once this PR gets merged, i.e: `Closes #1554` in the body of a commit
- [x] Followed the instructions in the [Contributing](CONTRIBUTING.md) document
- [x] Ran the unit/spec tests and ensured they still pass
- [x] Added tests to cover the new behaviour
- [ ] Updated the documentation to match the changes
- [ ] When possible, add an entry to the CHANGELOG file
- [ ] ~~Squashed your PR down to a single commit. You may forego this if the PR
  tries to address multiple issues. Though we prefer one PR per feature/fix,
  sometimes that's not feasible. In that case ensure that a single feature/fix
  and associated tests and documentation is bundled up in one commit~~ (Rebasing @gigadafud's commit so won't squash)

Optional, but extra points:
- [x] Added tests to ensure the old behaviour cannot accidentally be
  reintroduced

Confirmed casing from docs: https://www.iis.net/configreference/system.applicationhost/applicationpools/add/processmodel

---

### CODE REVIEW

**Comment by igalic** [comment]
tests failing :|

**Comment by juniorsysadmin** [comment]
You can ignore the Ruby 1.9.3 ones because that is a rest-client gem problem that needs solving, but tests run on the other Ruby versions are failing as well

**Comment by petems** [comment]
Ah, missed the casing in the manifest.

I'm going to add an acceptance test for this to double check, as we've had a few PR's for this so far

**Comment by juniorsysadmin** [comment]
@petems Is this still needed?

**Comment by petems** [comment]
Closing out old PR's, this is many years after the fact so I'm assuming it's super out of date! Closing 👍

**Pull request closed without merging**
